/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/button/BaseButton.vue')['default']
    BaseTooltip: typeof import('./src/components/button/BaseTooltip.vue')['default']
    FlashCleanHome: typeof import('./src/components/flashClean/FlashCleanHome.vue')['default']
    FlashCleanIndex: typeof import('./src/components/flashClean/FlashCleanIndex.vue')['default']
    IconButton: typeof import('./src/components/button/IconButton.vue')['default']
    MainNav: typeof import('./src/components/navigation/MainNav.vue')['default']
    NavItem: typeof import('./src/components/navigation/NavItem.vue')['default']
    NodeItem: typeof import('./src/components/nodes/NodeItem.vue')['default']
    NodesList: typeof import('./src/components/nodes/NodesList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggleButton: typeof import('./src/components/button/ThemeToggleButton.vue')['default']
  }
}
